//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.25 at 06:26:57 PM CET 
//

package fr.cnav.alfresco.as.capture.pdf.pli;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="lot_index_tech" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="pli">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rang_pli" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="pli_index_tech" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="pli_index_fonc" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="nb_doc_pli" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="document" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="rang_doc_pli" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="nbpage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="doc_index_tech">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="doc_index_fonc" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="page" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="rang_page" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="page_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="page_index_tech" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nb_doc" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="nb_pli" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "version", "lotIndexTech", "pli", "nbDoc", "nbPli" })
@XmlRootElement(name = "lot")
public class Lot {

	protected int version;
	@XmlElement(name = "lot_index_tech", required = true)
	protected List<Lot.LotIndexTech> lotIndexTech;
	@XmlElement(required = true)
	protected Lot.Pli pli;
	@XmlElement(name = "nb_doc")
	protected int nbDoc;
	@XmlElement(name = "nb_pli")
	protected int nbPli;

	/**
	 * Gets the value of the version property.
	 * 
	 */
	public int getVersion() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 */
	public void setVersion(int value) {
		this.version = value;
	}

	/**
	 * Gets the value of the lotIndexTech property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the lotIndexTech property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getLotIndexTech().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Lot.LotIndexTech }
	 * 
	 * 
	 */
	public List<Lot.LotIndexTech> getLotIndexTech() {
		if (lotIndexTech == null) {
			lotIndexTech = new ArrayList<Lot.LotIndexTech>();
		}
		return this.lotIndexTech;
	}

	/**
	 * Gets the value of the pli property.
	 * 
	 * @return possible object is {@link Lot.Pli }
	 * 
	 */
	public Lot.Pli getPli() {
		return pli;
	}

	/**
	 * Sets the value of the pli property.
	 * 
	 * @param value
	 *            allowed object is {@link Lot.Pli }
	 * 
	 */
	public void setPli(Lot.Pli value) {
		this.pli = value;
	}

	/**
	 * Gets the value of the nbDoc property.
	 * 
	 */
	public int getNbDoc() {
		return nbDoc;
	}

	/**
	 * Sets the value of the nbDoc property.
	 * 
	 */
	public void setNbDoc(int value) {
		this.nbDoc = value;
	}

	/**
	 * Gets the value of the nbPli property.
	 * 
	 */
	public int getNbPli() {
		return nbPli;
	}

	/**
	 * Sets the value of the nbPli property.
	 * 
	 */
	public void setNbPli(int value) {
		this.nbPli = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "nom", "val" })
	public static class LotIndexTech {

		@XmlElement(required = true)
		protected String nom;
		@XmlElement(required = true)
		protected String val;

		/**
		 * Gets the value of the nom property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNom() {
			return nom;
		}

		/**
		 * Sets the value of the nom property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNom(String value) {
			this.nom = value;
		}

		/**
		 * Gets the value of the val property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getVal() {
			return val;
		}

		/**
		 * Sets the value of the val property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setVal(String value) {
			this.val = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="rang_pli" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *         &lt;element name="pli_index_tech" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="pli_index_fonc" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="nb_doc_pli" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *         &lt;element name="document" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="rang_doc_pli" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                   &lt;element name="nbpage" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                   &lt;element name="doc_index_tech">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="doc_index_fonc" maxOccurs="unbounded">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="page" maxOccurs="unbounded">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="rang_page" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                             &lt;element name="page_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="page_index_tech" maxOccurs="unbounded">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;sequence>
	 *                                       &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                     &lt;/sequence>
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "rangPli", "pliIndexTech", "pliIndexFonc", "nbDocPli", "document" })
	public static class Pli {

		@XmlElement(name = "rang_pli")
		protected int rangPli;
		@XmlElement(name = "pli_index_tech", required = true)
		protected List<Lot.Pli.PliIndexTech> pliIndexTech;
		@XmlElement(name = "pli_index_fonc", required = true)
		protected List<Lot.Pli.PliIndexFonc> pliIndexFonc;
		@XmlElement(name = "nb_doc_pli")
		protected int nbDocPli;
		@XmlElement(required = true)
		protected List<Lot.Pli.Document> document;

		/**
		 * Gets the value of the rangPli property.
		 * 
		 */
		public int getRangPli() {
			return rangPli;
		}

		/**
		 * Sets the value of the rangPli property.
		 * 
		 */
		public void setRangPli(int value) {
			this.rangPli = value;
		}

		/**
		 * Gets the value of the pliIndexTech property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the pliIndexTech property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getPliIndexTech().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Lot.Pli.PliIndexTech }
		 * 
		 * 
		 */
		public List<Lot.Pli.PliIndexTech> getPliIndexTech() {
			if (pliIndexTech == null) {
				pliIndexTech = new ArrayList<Lot.Pli.PliIndexTech>();
			}
			return this.pliIndexTech;
		}

		/**
		 * Gets the value of the pliIndexFonc property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the pliIndexFonc property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getPliIndexFonc().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Lot.Pli.PliIndexFonc }
		 * 
		 * 
		 */
		public List<Lot.Pli.PliIndexFonc> getPliIndexFonc() {
			if (pliIndexFonc == null) {
				pliIndexFonc = new ArrayList<Lot.Pli.PliIndexFonc>();
			}
			return this.pliIndexFonc;
		}

		/**
		 * Gets the value of the nbDocPli property.
		 * 
		 */
		public int getNbDocPli() {
			return nbDocPli;
		}

		/**
		 * Sets the value of the nbDocPli property.
		 * 
		 */
		public void setNbDocPli(int value) {
			this.nbDocPli = value;
		}

		/**
		 * Gets the value of the document property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the document property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getDocument().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Lot.Pli.Document }
		 * 
		 * 
		 */
		public List<Lot.Pli.Document> getDocument() {
			if (document == null) {
				document = new ArrayList<Lot.Pli.Document>();
			}
			return this.document;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="rang_doc_pli" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *         &lt;element name="nbpage" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *         &lt;element name="doc_index_tech">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="doc_index_fonc" maxOccurs="unbounded">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="page" maxOccurs="unbounded">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="rang_page" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                   &lt;element name="page_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="page_index_tech" maxOccurs="unbounded">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;sequence>
		 *                             &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                           &lt;/sequence>
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "rangDocPli", "nbpage", "docIndexTech", "docIndexFonc", "page" })
		public static class Document {

			@XmlElement(name = "rang_doc_pli")
			protected int rangDocPli;
			protected int nbpage;
			@XmlElement(name = "doc_index_tech", required = true)
			protected Lot.Pli.Document.DocIndexTech docIndexTech;
			@XmlElement(name = "doc_index_fonc", required = true)
			protected List<Lot.Pli.Document.DocIndexFonc> docIndexFonc;
			@XmlElement(required = true)
			protected List<Lot.Pli.Document.Page> page;

			/**
			 * Gets the value of the rangDocPli property.
			 * 
			 */
			public int getRangDocPli() {
				return rangDocPli;
			}

			/**
			 * Sets the value of the rangDocPli property.
			 * 
			 */
			public void setRangDocPli(int value) {
				this.rangDocPli = value;
			}

			/**
			 * Gets the value of the nbpage property.
			 * 
			 */
			public int getNbpage() {
				return nbpage;
			}

			/**
			 * Sets the value of the nbpage property.
			 * 
			 */
			public void setNbpage(int value) {
				this.nbpage = value;
			}

			/**
			 * Gets the value of the docIndexTech property.
			 * 
			 * @return possible object is {@link Lot.Pli.Document.DocIndexTech }
			 * 
			 */
			public Lot.Pli.Document.DocIndexTech getDocIndexTech() {
				return docIndexTech;
			}

			/**
			 * Sets the value of the docIndexTech property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link Lot.Pli.Document.DocIndexTech }
			 * 
			 */
			public void setDocIndexTech(Lot.Pli.Document.DocIndexTech value) {
				this.docIndexTech = value;
			}

			/**
			 * Gets the value of the docIndexFonc property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the docIndexFonc property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getDocIndexFonc().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link Lot.Pli.Document.DocIndexFonc }
			 * 
			 * 
			 */
			public List<Lot.Pli.Document.DocIndexFonc> getDocIndexFonc() {
				if (docIndexFonc == null) {
					docIndexFonc = new ArrayList<Lot.Pli.Document.DocIndexFonc>();
				}
				return this.docIndexFonc;
			}

			/**
			 * Gets the value of the page property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the page property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getPage().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link Lot.Pli.Document.Page }
			 * 
			 * 
			 */
			public List<Lot.Pli.Document.Page> getPage() {
				if (page == null) {
					page = new ArrayList<Lot.Pli.Document.Page>();
				}
				return this.page;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "nom", "val" })
			public static class DocIndexFonc {

				@XmlElement(required = true)
				protected String nom;
				@XmlElement(required = true)
				protected Object val;

				/**
				 * Gets the value of the nom property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getNom() {
					return nom;
				}

				/**
				 * Sets the value of the nom property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setNom(String value) {
					this.nom = value;
				}

				/**
				 * Gets the value of the val property.
				 * 
				 * @return possible object is {@link Object }
				 * 
				 */
				public Object getVal() {
					return val;
				}

				/**
				 * Sets the value of the val property.
				 * 
				 * @param value
				 *            allowed object is {@link Object }
				 * 
				 */
				public void setVal(Object value) {
					this.val = value;
				}

			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "nom", "val" })
			public static class DocIndexTech {

				@XmlElement(required = true)
				protected String nom;
				@XmlElement(required = true)
				protected String val;

				/**
				 * Gets the value of the nom property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getNom() {
					return nom;
				}

				/**
				 * Sets the value of the nom property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setNom(String value) {
					this.nom = value;
				}

				/**
				 * Gets the value of the val property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getVal() {
					return val;
				}

				/**
				 * Sets the value of the val property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setVal(String value) {
					this.val = value;
				}

			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="rang_page" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *         &lt;element name="page_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="page_index_tech" maxOccurs="unbounded">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;sequence>
			 *                   &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                 &lt;/sequence>
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "rangPage", "pagePath", "pageIndexTech" })
			public static class Page {

				@XmlElement(name = "rang_page")
				protected int rangPage;
				@XmlElement(name = "page_path", required = true)
				protected String pagePath;
				@XmlElement(name = "page_index_tech", required = true)
				protected List<Lot.Pli.Document.Page.PageIndexTech> pageIndexTech;

				/**
				 * Gets the value of the rangPage property.
				 * 
				 */
				public int getRangPage() {
					return rangPage;
				}

				/**
				 * Sets the value of the rangPage property.
				 * 
				 */
				public void setRangPage(int value) {
					this.rangPage = value;
				}

				/**
				 * Gets the value of the pagePath property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getPagePath() {
					return pagePath;
				}

				/**
				 * Sets the value of the pagePath property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setPagePath(String value) {
					this.pagePath = value;
				}

				/**
				 * Gets the value of the pageIndexTech property.
				 * 
				 * <p>
				 * This accessor method returns a reference to the live list,
				 * not a snapshot. Therefore any modification you make to the
				 * returned list will be present inside the JAXB object. This is
				 * why there is not a <CODE>set</CODE> method for the
				 * pageIndexTech property.
				 * 
				 * <p>
				 * For example, to add a new item, do as follows:
				 * 
				 * <pre>
				 * getPageIndexTech().add(newItem);
				 * </pre>
				 * 
				 * 
				 * <p>
				 * Objects of the following type(s) are allowed in the list
				 * {@link Lot.Pli.Document.Page.PageIndexTech }
				 * 
				 * 
				 */
				public List<Lot.Pli.Document.Page.PageIndexTech> getPageIndexTech() {
					if (pageIndexTech == null) {
						pageIndexTech = new ArrayList<Lot.Pli.Document.Page.PageIndexTech>();
					}
					return this.pageIndexTech;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;sequence>
				 *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *       &lt;/sequence>
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "nom", "val" })
				public static class PageIndexTech {

					@XmlElement(required = true)
					protected String nom;
					@XmlElement(required = true)
					protected String val;

					/**
					 * Gets the value of the nom property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getNom() {
						return nom;
					}

					/**
					 * Sets the value of the nom property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setNom(String value) {
						this.nom = value;
					}

					/**
					 * Gets the value of the val property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getVal() {
						return val;
					}

					/**
					 * Sets the value of the val property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setVal(String value) {
						this.val = value;
					}

				}

			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "nom", "val" })
		public static class PliIndexFonc {

			@XmlElement(required = true)
			protected String nom;
			@XmlElement(required = true)
			protected Object val;

			/**
			 * Gets the value of the nom property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getNom() {
				return nom;
			}

			/**
			 * Sets the value of the nom property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setNom(String value) {
				this.nom = value;
			}

			/**
			 * Gets the value of the val property.
			 * 
			 * @return possible object is {@link Object }
			 * 
			 */
			public Object getVal() {
				return val;
			}

			/**
			 * Sets the value of the val property.
			 * 
			 * @param value
			 *            allowed object is {@link Object }
			 * 
			 */
			public void setVal(Object value) {
				this.val = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="val" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "nom", "val" })
		public static class PliIndexTech {

			@XmlElement(required = true)
			protected String nom;
			@XmlElement(required = true)
			protected String val;

			/**
			 * Gets the value of the nom property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getNom() {
				return nom;
			}

			/**
			 * Sets the value of the nom property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setNom(String value) {
				this.nom = value;
			}

			/**
			 * Gets the value of the val property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getVal() {
				return val;
			}

			/**
			 * Sets the value of the val property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setVal(String value) {
				this.val = value;
			}

		}

	}

}
