//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.25 at 06:26:57 PM CET 
//

package fr.cnav.alfresco.as.capture.pdf.pli;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the fr.cnav.alfresco.cpp.pdf.metier package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: fr.cnav.alfresco.cpp.pdf.metier
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Lot }
	 * 
	 */
	public Lot createLot() {
		return new Lot();
	}

	/**
	 * Create an instance of {@link Lot.Pli }
	 * 
	 */
	public Lot.Pli createLotPli() {
		return new Lot.Pli();
	}

	/**
	 * Create an instance of {@link Lot.Pli.Document }
	 * 
	 */
	public Lot.Pli.Document createLotPliDocument() {
		return new Lot.Pli.Document();
	}

	/**
	 * Create an instance of {@link Lot.Pli.Document.Page }
	 * 
	 */
	public Lot.Pli.Document.Page createLotPliDocumentPage() {
		return new Lot.Pli.Document.Page();
	}

	/**
	 * Create an instance of {@link Lot.LotIndexTech }
	 * 
	 */
	public Lot.LotIndexTech createLotLotIndexTech() {
		return new Lot.LotIndexTech();
	}

	/**
	 * Create an instance of {@link Lot.Pli.PliIndexTech }
	 * 
	 */
	public Lot.Pli.PliIndexTech createLotPliPliIndexTech() {
		return new Lot.Pli.PliIndexTech();
	}

	/**
	 * Create an instance of {@link Lot.Pli.PliIndexFonc }
	 * 
	 */
	public Lot.Pli.PliIndexFonc createLotPliPliIndexFonc() {
		return new Lot.Pli.PliIndexFonc();
	}

	/**
	 * Create an instance of {@link Lot.Pli.Document.DocIndexTech }
	 * 
	 */
	public Lot.Pli.Document.DocIndexTech createLotPliDocumentDocIndexTech() {
		return new Lot.Pli.Document.DocIndexTech();
	}

	/**
	 * Create an instance of {@link Lot.Pli.Document.DocIndexFonc }
	 * 
	 */
	public Lot.Pli.Document.DocIndexFonc createLotPliDocumentDocIndexFonc() {
		return new Lot.Pli.Document.DocIndexFonc();
	}

	/**
	 * Create an instance of {@link Lot.Pli.Document.Page.PageIndexTech }
	 * 
	 */
	public Lot.Pli.Document.Page.PageIndexTech createLotPliDocumentPagePageIndexTech() {
		return new Lot.Pli.Document.Page.PageIndexTech();
	}

}
